<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/admin/login.css')
                        ->prependStylesheet($this->basePath() . '/plugins/uniform/css/uniform.default.css')
                        ->prependStylesheet($this->basePath() . '/css/style-responsive.css')
                        ->prependStylesheet($this->basePath() . '/css/themes/default.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/style-metro.css')
                        ->prependStylesheet($this->basePath() . '/plugins/font-awesome/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/plugins/bootstrap/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/plugins/bootstrap/css/bootstrap-responsive.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()                 
            ->prependFile($this->basePath() . '/plugins/jquery-validation/dist/jquery.validate.min.js')           
            ->prependFile($this->basePath() . '/plugins/uniform/jquery.uniform.min.js')
            ->prependFile($this->basePath() . '/plugins/jquery.cookie.min.js')  
            ->prependFile($this->basePath() . '/plugins/jquery.blockui.min.js')    
            ->prependFile($this->basePath() . '/plugins/jquery-slimscroll/jquery.slimscroll.min.js')
            ->prependFile($this->basePath() . '/plugins/excanvas.min.js', 'text/javascript', array('conditional' => 'lt IE 9',)) 
            ->prependFile($this->basePath() . '/plugins/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/plugins/bootstrap/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/plugins/jquery-ui/jquery-ui-1.10.1.custom.min.js') 
            ->prependFile($this->basePath() . '/plugins/jquery-migrate-1.2.1.min.js') 
            ->prependFile($this->basePath() . '/plugins/jquery-1.10.1.min.js'); ?>

    </head>
    <body>
        <?php // <-- Update this !!
$this->navigation('navigation')
    ->breadcrumbs()->setMinDepth(0);  ?>
    
        <?php echo $this->partial('layout/header');?> 
        <?php echo $this->partial('layout/sidemenu');?>
        
        <?php echo $this->partial('layout/message');?>
        <?php echo $this->content; ?> 
        <?php echo $this->partial('layout/footer');?> 
        <?php echo $this->inlineScript() ?>
    </body>
</html>
