<form class="form-horizontal" role="form" method="post">
    <?php $form->prepare();?>
  <div class="form-group"> 
    <label for="inputEmail1" class="col-lg-2 control-label">Username</label>
    <div class="col-lg-10">
      <?php echo $this->formRow($form->get('username'));?>
    </div>
  </div>
  <div class="form-group">
    <label for="inputPassword1" class="col-lg-2 control-label">Password</label>
    <div class="col-lg-10">
        <?php echo $this->formRow($form->get('password'));?>
      
    </div>
  </div> 
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <button type="submit" class="btn btn-default">Sign in</button>
    </div>
  </div>
</form>
