<?php
 $this->headLink()->appendStylesheet($this->basePath().'/plugins/select2/select2_metro.css')
 ->appendStylesheet($this->basePath().'/plugins/chosen-bootstrap/chosen/chosen.css')
 ->appendStylesheet($this->basePath().'/plugins/jquery-multi-select/css/multi-select-metro.css')
 ->appendStylesheet($this->basePath().'/plugins/jquery-multi-select/css/multi-select-metro.css')
 ->appendStylesheet($this->basePath().'/plugins/jquery-multi-select/css/multi-select-metro.css')
 ->appendStylesheet($this->basePath().'/plugins/jquery-multi-select/css/multi-select-metro.css')
 ->appendStylesheet($this->basePath().'/plugins/jquery-multi-select/css/multi-select-metro.css')
 ->appendStylesheet($this->basePath().'/plugins/jquery-multi-select/css/multi-select-metro.css')
 ->appendStylesheet($this->basePath().'/plugins/jquery-multi-select/css/multi-select-metro.css');?>
 <?php
 $countries = array();
 foreach($countrys as $country):?>
 <?php $countries[] = array('code' => $country->code,'default_name' => $country->default_name); ?> 
 <?php endforeach;?>
<div class="page-header-fixed"> 
	<!-- BEGIN CONTAINER -->
	<div class="page-container">
		<!-- BEGIN PAGE -->
                <div class="page-content">
                    <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<div id="portlet-config" class="modal hide">
				<div class="modal-header">
					<button data-dismiss="modal" class="close" type="button"></button>
					<h3>portlet Settings</h3>
				</div>
				<div class="modal-body">
					<p>Here will be a configuration form</p>
				</div>
			</div>
			<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<!-- BEGIN PAGE CONTAINER-->
			<div class="container-fluid">
				<!-- BEGIN PAGE HEADER-->   
				<div class="row-fluid scroller_anchor">
					<div class="span12">  
						<h3 class="page-title">
							Settings / General settings
							 <small>advance form layout samples</small>
						</h3>
						<ul class="breadcrumb">
							<li>
								<i class="icon-home"></i>
								<a href="index.html">Home</a> 
								<span class="icon-angle-right"></span>
							</li>
							<li>
								<a href="#">Form Stuff</a>
								<span class="icon-angle-right"></span>
							</li>
							<li><a href="#">Form Layouts</a></li>
						</ul>
					</div>
				</div>
				<!-- END PAGE HEADER-->
				
				<div class="row-fluid fixedButton">
						     <div class="form-actions" style="margin-top:0; border: none;">
							 <button type="submit" class="btn blue" style="float: right;">Submit</button>
							 <button type="button" class="btn" style="float: right; margin-right: 5px;">Cancel</button>                            
						 </div>
				</div>
				<!-- BEGIN PAGE CONTENT-->
				<div class="row-fluid">
					<div class="span12"> 
						<div class="portlet box blue">
							<div class="portlet-title">
								<div class="caption"><i class="icon-reorder"></i>Country options</div>
								<div class="tools">
									<a href="javascript:;" class="collapse"></a>
									<a href="#portlet-config" data-toggle="modal" class="config"></a>
									<a href="javascript:;" class="reload"></a>
									<a href="javascript:;" class="remove"></a>
								</div>
							</div>
							<div class="portlet-body form">
								<!-- BEGIN FORM-->
								<form action="#" class="form-horizontal">
									<div class="control-group">
										<label class="control-label">Default country</label>
																				<div class="controls">
											<select data-placeholder="Your Default Country" class="chosen span6" tabindex="-1" id="selS0V" name="settings[general][default_country]">
												<option value=""></option>
												<?php foreach($countries as $country):?>
                                                                                                <option value="<?php echo $country['code'];?>"><?php echo $country['default_name'];?></option>
												<?php endforeach;?> 
											</select>
										</div>

									</div>
									<div class="control-group">
										<label class="control-label">Allowed countries</label>
																				<div class="controls">
											<select data-placeholder="Choose country" class="chosen span6" multiple="multiple" tabindex="6" name="settings[general][allowed_country]">
												<option value=""></option>
												<?php foreach($countries as $country):?>
                                                                                                <option value="<?php echo $country['code'];?>"><?php echo $country['default_name'];?></option>
												<?php endforeach;?> 
											</select>
										</div>

									</div>
									 
									
								</form>
								<!-- END FORM-->       
							</div>
						</div>

					</div>
				</div>
                                
                                <!--2-->
                                    <div class="row-fluid">
					<div class="span12"> 
						<div class="portlet box green">
							<div class="portlet-title">
								<div class="caption"><i class="icon-reorder"></i>Locale options</div>
								<div class="tools">
									<a href="javascript:;" class="collapse"></a>
									<a href="#portlet-config" data-toggle="modal" class="config"></a>
									<a href="javascript:;" class="reload"></a>
									<a href="javascript:;" class="remove"></a>
								</div>
							</div>
							<div class="portlet-body form">
								<!-- BEGIN FORM-->
								<form action="#" class="form-horizontal">
									<div class="control-group">
										<label class="control-label">TimeZone</label>
                                                                                    <div class="controls">
											<select data-placeholder="Your Favorite Football Team" class="chosen span6" tabindex="-1" id="selS1F" name="settings[general][timezone]">
												<option value=""></option>
										<?php foreach($timezone as $value => $zone):?>
											 <option value="<?php echo $value;?>"><?php echo $zone;?></option>
											 <?php endforeach;?>
											</select>
										</div>

									</div>
                                                                        <div class="control-group">
										<label class="control-label">Locale</label>
                                                                                    <div class="controls">
											<select data-placeholder="Your Favorite Football Team" class="chosen span6" tabindex="-1" id="selLAF"  name="settings[general][locale]">
											 <?php foreach($locale as $value => $local):?>
											 <option value="<?php echo $value;?>"><?php echo $local;?></option>
											 <?php endforeach;?>
</select> 	 
										</div>

									</div>

									<div class="control-group">
										<label class="control-label">Working Days</label>
																				<div class="controls">
											<select data-placeholder="Working days" class="chosen span6" multiple="multiple" tabindex="6"    name="settings[general][working_days]">
												<option value=""></option>
												<?php foreach($workingdays as $key => $days):?>
												<option value="<?php echo $key;?>"><?php echo $days;?></option>
												<?php endforeach;?> 
											</select>
										</div>

									</div>
									 
									
								</form>
								<!-- END FORM-->       
							</div>
						</div>

					</div>
				</div>
                                    
                                <!--3-->
                                    <div class="row-fluid">
					<div class="span12"> 
						<div class="portlet box red">
							<div class="portlet-title">
								<div class="caption"><i class="icon-reorder"></i>Site Information</div>
								<div class="tools">
									<a href="javascript:;" class="collapse"></a>
									<a href="#portlet-config" data-toggle="modal" class="config"></a>
									<a href="javascript:;" class="reload"></a>
									<a href="javascript:;" class="remove"></a>
								</div>
							</div>
							<div class="portlet-body form">
								<!-- BEGIN FORM-->
								<form action="#" class="form-horizontal">
									<div class="control-group">
										<label class="control-label">Sitename</label>
                                                                                    <div class="controls">
											<input type="text" id="sitename" name="settings[general][sitename]" class="m-wrap span12" placeholder="Site Name">
										</div> 
									</div>
                                                                        <div class="control-group">
										<label class="control-label">Telephone</label>
                                                                                    <div class="controls">
											<input type="text" id="telephone" name="settings[general][telephone]" class="m-wrap span12" placeholder="Telephone">
										</div> 
									</div>
                                                                        <div class="control-group">
										<label class="control-label">Country</label>
                                                                                    <div class="controls">
											<select data-placeholder="Choose country" class="chosen span6" tabindex="-1" id="selK2I" name="settings[general][site_country]">
												<option value=""></option>
												<?php foreach($countries as $country):?>
                                                                                                <option value="<?php echo $country['code'];?>"><?php echo $country['default_name'];?></option>
												<?php endforeach;?> 
											</select>
										</div>

									</div> 
									 <div class="control-group">
										<label class="control-label">Textarea</label>
										<div class="controls">
											<textarea name="settings[general][site_address]" class="span6 m-wrap" rows="3"></textarea>
										</div>
									</div>
									
								</form>
								<!-- END FORM-->       
							</div>
						</div>

					</div>
				</div>
                                
				<!-- END PAGE CONTENT-->         
			</div>
			<!-- END PAGE CONTAINER-->
                </div>
        </div>
</div>
  <?php  $this->headScript()
            ->appendFile($this->basePath().  '/plugins/jquery-multi-select/js/jquery.multi-select.js')
            ->appendFile($this->basePath().  '/plugins/chosen-bootstrap/chosen/chosen.jquery.min.js')
            ->appendFile($this->basePath().  '/plugins/select2/select2.min.js')
            ->appendFile($this->basePath().  '/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js')
            ->appendFile($this->basePath().  '/plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js')
            ->appendFile($this->basePath() . '/js/admin/app.js') 
            ->appendFile($this->basePath() . '/js/admin/form-components.js')
            ->appendFile($this->basePath().  '/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js')
            ->appendFile($this->basePath().  '/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js')
            ->appendFile($this->basePath().  '/plugins/jquery.input-ip-address-control-1.0.min.js')
            ->appendFile($this->basePath().  '/plugins/select2/select2.min.js')
            ->appendFile($this->basePath().  '/plugins/select2/select2.min.js')
            ->appendFile($this->basePath().  '/plugins/select2/select2.min.js')
            ->appendFile($this->basePath().  '/plugins/select2/select2.min.js')
            ->appendFile($this->basePath().  '/plugins/select2/select2.min.js')
            ->appendFile($this->basePath().  '/plugins/select2/select2.min.js')
            ->appendFile($this->basePath().  '/plugins/select2/select2.min.js')
            ->appendFile($this->basePath().  '/plugins/select2/select2.min.js');
        ?>
        <script>
		jQuery(document).ready(function() {    
		   App.init(); // initlayout and core plugins
		    FormComponents.init();

		});
	</script>